[package]
name = "simulator"
version = "0.1.0"
edition = "2018"

[dependencies]
radix-engine = { path = "../radix-engine" }
scrypto = { path = "../scrypto", features = ["serde_std"] }
sbor = { path = "../sbor" }
transaction-manifest = { path = "../transaction-manifest" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
clap = { version = "2.33" }
dirs = { version = "4.0" }
colored = { version = "2.0" }
uuid = { version = "0.8", features = ["v4"] }
hex = { version = "0.4" }

[[bin]]
name = "resim"
path = "src/bin/resim.rs"

[[bin]]
name = "scrypto"
path = "src/bin/scrypto.rs"