[package]
name = "radix-engine"
version = "0.1.0"
authors = ["Yulong Wu <yulong@radixdlt.com>"]
edition = "2018"

[dependencies]
scrypto = { version = "0.1", path = "../scrypto" }
sbor = { version = "0.1", path = "../sbor" }
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }
clap = { version = "2.33" }
wasmi = { version = "0.9" }
dirs = { version = "3.0" }
colored = { version = "2.0" }
hashbrown = { version = "0.11" }
uuid = { version = "0.8", features = ["v4"] }

[features]
# Enable this feature to use a JSON-based ledger
json = ["serde", "serde_json"]