[package]
name = "radix-engine"
version = "0.1.0"
edition = "2018"

[dependencies]
sbor = { version = "0.1", path = "../sbor", default-features = false }
scrypto = { version = "0.1", path = "../scrypto", default-features = false}
wasmi = { version = "0.9", default-features = false }
colored = { version = "2.0", default-features = false }
lru = { version = "0.6" }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std", "scrypto/std", "wasmi/std"]
alloc = ["sbor/alloc", "scrypto/alloc", "wasmi/core"]
