[package]
name = "scrypto-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = { version = "1.0" }
uuid = { version = "0.8", features = ["v4"] }
serde = { version = "1.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
sbor = { version = "0.1", path = "../sbor", default-features = false }
scrypto-abi = { version = "0.1", path = "../scrypto-abi", default-features = false }

[features]
# Currenlty, dependencies of procedrual macros are imported to host crates. This may accidentally 
# enable unwanted features of host dependencies, i.e. `serde`, `serde_json`, `sbor`å and `scrypto-abi`.
# 
# To work around with it, we've added features `std` and `alloc` for `scrypto-derive`, even
# though it only works under `std` environment.
#
# See:
# - https://github.com/rust-lang/cargo/issues/5730
# - https://github.com/rust-lang/cargo/issues/7915
#
default = ["std"]
std = [
    "serde/std", "serde_json/std", 
    "sbor/std", "sbor/scrypto_std", "sbor/json_std", 
    "scrypto-abi/std", "scrypto-abi/json_std"
]
alloc = [
    "serde/alloc", "serde_json/alloc", 
    "sbor/alloc", "sbor/scrypto_alloc", "sbor/json_alloc", 
    "scrypto-abi/alloc", "scrypto-abi/json_alloc"
]

trace = []