[package]
name = "scrypto-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = { version = "1.0" }
uuid = { version = "0.8", features = ["v4"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
sbor = { version = "0.1", path = "../sbor", default-features = false, features = ["json", "alloc"] }
scrypto-abi = { version = "0.1", path = "../scrypto-abi", default-features = false, features = ["json", "alloc"] }

[features]
trace = []