[package]
name = "scrypto-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
scrypto-abi = { version = "0.1", path = "../scrypto-abi", default-features = false }
uuid = { version = "0.8", features = ["v4"] }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "scrypto-abi/std"]
alloc = ["serde/alloc", "serde_json/alloc", "scrypto-abi/alloc"]
trace = []