[package]
name = "sbor"
version = "0.1.0"
edition = "2018"

[dependencies]
sbor-derive = { version = "0.1", path = "../sbor-derive" }
hashbrown = { version = "0.11", optional = true } 
serde = { version = "1.0", default-features = false, optional = true }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = []
alloc = ["hashbrown"]

# Enable tracing
trace = ["sbor-derive/trace"]

# Enable serde annotations by either `json_std` or `json_alloc`.
# TODO: use weak depedency feature once it's stablized, https://github.com/rust-lang/cargo/issues/8832 
json_std = ["serde", "serde/std", "serde/derive"]
json_alloc = ["serde", "serde/alloc", "serde/derive"]
