[package]
name = "sbor"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0", default-features = false, optional = true }
serde_json = { version = "1.0", default-features = false, optional = true }
sbor-derive = { version = "0.1", path = "../sbor-derive", default-features = false, optional = true }
generic-array = "0.14.4"

[features]
default = []

# Enable this feature to use `Describe`, `Encode` and `Decode` derives.
derive = ["sbor-derive"]

# Enable this feature to turn on tracing.
trace = ["sbor-derive/trace"]

# For JSON annotations, enable either `["json", "std"]` or `["json", "alloc"]`.
json = ["serde", "serde/derive", "serde_json"]
std = ["serde/std", "serde_json/std"]
alloc = ["serde/alloc", "serde_json/alloc"]

