[package]
name = "sbor"
version = "0.1.0"
edition = "2018"

[dependencies]
sbor-derive = { version = "0.1", path = "../sbor-derive" }
serde = { version = "1.0", default-features = false, optional = true }

[features]
default = []

# Enable tracing
trace = ["sbor-derive/trace"]

# Enable serde annotations by `["json", "std"]` or `["json", "alloc"]`
json = ["serde", "serde/derive"]
std = ["serde/std"]
alloc = ["serde/alloc"]
