[package]
name = "scrypto-abi"
version = "0.1.0"
edition = "2018"

[dependencies]
sbor = { version = "0.1", path = "../sbor", default-features = false }
serde = { version = "1.0", default-features = false, optional = true }

[features]
# You should enable either `std` or `alloc`
default = ["std"]
std = ["sbor/std"]
alloc = ["sbor/alloc"]

# Enable serde annotations by either `json_std` or `json_alloc`.
# TODO: use weak depedency feature once it's stablized, https://github.com/rust-lang/cargo/issues/8832 
json_std = ["serde", "serde/std", "serde/derive", "sbor/json_std"]
json_alloc = ["serde", "serde/alloc", "serde/derive", "sbor/json_alloc"]