[package]
name = "scrypto-abi"
version = "0.1.0"
edition = "2018"

[dependencies]
sbor = { version = "0.1", path = "../sbor", default-features = false }
serde = { version = "1.0", default-features = false, optional = true }

[features]
default = []

# Enable serde annotations by `["json", "std"]` or `["json", "alloc"]`
json = ["serde", "sbor/json"]
std = ["serde/std"]
alloc = ["serde/alloc"]