[package]
name = "scrypto-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
# Not enabling feature `derive` so that we can trace the compilation process
scrypto = { version = "0.1", path = "../scrypto", default-features = false, features = ["abi"] }
scrypto-derive = { version = "0.1", path = "../scrypto-derive", default-features = false, features = ["trace"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "scrypto/std"]
alloc = ["serde/alloc", "serde_json/alloc", "scrypto/alloc"]