[package]
name = "scrypto-tests"
version = "0.1.0"
edition = "2018"

[dependencies]
scrypto = { version = "0.1", path = "../scrypto" }
sbor = { version = "0.1", path = "../sbor" }

[dev-dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "scrypto/std"]
alloc = ["serde/alloc", "serde_json/alloc", "scrypto/alloc"]