[package]
name = "scrypto-sdk"
version = "0.1.0"
edition = "2018"

[dependencies]
# Serialization
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0", default-features = false }
bincode_core = { git = "https://github.com/bincode-org/bincode-core.git", default-features = false }

# Uint256
uint = { version = "0.9", default-features = false }

# SHA256
sha2 = { version="0.9", default-features = false }

[features]
default = ["std"]
std = ["serde/std", "serde_json/std", "bincode_core/std"]
alloc = ["serde/alloc", "serde_json/alloc", "bincode_core/alloc"]