name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  sbor-unit-tests:
    name: Run SBOR unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: sbor
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: sbor
    - name: Run derive tests
      run: cargo test --verbose
      working-directory: sbor-derive
  sbor-integration-tests:
    name: Run SBOR integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: sbor-tests
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: sbor-tests
    - name: Run bench
      run: cargo bench --verbose
      working-directory: sbor-tests
  scrypto-unit-tests:
    name: Run Scrypto unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto
    - name: Run abi tests
      run: cargo test --verbose
      working-directory: scrypto-abi
    - name: Run derive tests
      run: cargo test --verbose
      working-directory: scrypto-derive
  scrypto-integration-tests:
    name: Run Scrypto integration tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto-tests
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto-tests
  scrypto-examples:
    name: Run Scrypto examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Add wasm target (nightly)
      run: rustup +nightly target add wasm32-unknown-unknown
    - name: Build account
      run: cargo build --target wasm32-unknown-unknown --release
      working-directory: assets/account
    - name: Build system
      run: cargo build --target wasm32-unknown-unknown --release
      working-directory: assets/system
    - name: Build helloworld
      run: cargo build --target wasm32-unknown-unknown --release
      working-directory: examples/helloworld
    - name: Build no_std
      run: cargo build --target wasm32-unknown-unknown --release
      working-directory: examples/no_std
    - name: Build gumball machine
      run: cargo build --target wasm32-unknown-unknown --release
      working-directory: examples/gumball-machine
    - name: Build gumball machine vendor
      run: cargo build --target wasm32-unknown-unknown --release
      working-directory: examples/gumball-machine-vendor
    - name: Build radiswap
      run: cargo build --target wasm32-unknown-unknown --release
      working-directory: examples/radiswap
  radix-engine:
    name: Run Radix Engine tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Run tests
      run: cargo test --verbose
      working-directory: radix-engine
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: radix-engine
    - name: Run bench
      run: cargo bench
      working-directory: radix-engine
  simulator-rev2:
    name: Run Simulator tests (rev2)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Run tests
      run: bash ./tests/rev2.sh
      working-directory: simulator
  simulator-scrypto:
    name: Run Simulator tests (scrypto)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Run tests
      run: bash ./tests/scrypto.sh
      working-directory: simulator
