name: CI

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-stdlib:
    name: Test standard library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto
  test-macros:
    name: Test macros
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto-macros
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto-macros
