name: CI

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  sbor-unit-tests:
    name: Run SBOR unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: sbor
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: sbor
    - name: Run derive tests
      run: cargo test --verbose
      working-directory: sbor-derive
  sbor-integration-tests:
    name: Run SBOR integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: sbor-tests
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: sbor-tests
  scrypto-unit-tests:
    name: Run Scrypto unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto
    - name: Run abi tests
      run: cargo test --verbose
      working-directory: scrypto-abi
    - name: Run derive tests
      run: cargo test --verbose
      working-directory: scrypto-derive
    - name: Run types tests
      run: cargo test --verbose
      working-directory: scrypto-types
  scrypto-integration-tests:
    name: Run Scrypto integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto-tests
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto-tests
  scrypto-examples:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Add wasm target (nightly)
      run: rustup +nightly target add wasm32-unknown-unknown
    - name: Build helloworld
      run: cargo build --target wasm32-unknown-unknown
      working-directory: examples/helloworld
    - name: Build no_std
      run: cargo build --target wasm32-unknown-unknown
      working-directory: examples/no_std
  radix-engine:
    name: Run Radix Engine tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Run tests
      run: cargo test --verbose
      working-directory: radix-engine
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: radix-engine
  simulator:
    name: Build simulator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo run -- help
      working-directory: simulator
