name: CI

on: [pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  sbor-unit-tests:
    name: Run SBOR unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: sbor
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features json,alloc
      working-directory: sbor
  sbor-derive-tests:
    name: Run SBOR derive tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: sbor-derive
  sbor-integration-tests:
    name: Run SBOR integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: sbor-tests
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: sbor-tests
    - name: Run derive tests
      run: cargo test --verbose
      working-directory: sbor-derive
  scrypto-unit-tests:
    name: Run Scrypto unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto
  scrypto-derive-tests:
    name: Run Scrypto derive tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto-derive
  scrypto-integration-tests:
    name: Run Scrypto integration tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --verbose
      working-directory: scrypto-tests
    - name: Run tests (no_std)
      run: cargo test --verbose --no-default-features --features alloc
      working-directory: scrypto-tests
  scrypto-examples:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build helloworld
      run: cargo build --target wasm32-unknown-unknown
      working-directory: examples/helloworld
    - name: Build no_std
      run: cargo build --target wasm32-unknown-unknown
      working-directory: examples/no_std
